spring:
  main:
    web-application-type: none
  application:
    ui:
      title: Reacher Application

reacher-sources:
  discogs:
    user: ElishyahIsrael
    token: QLuWLCeELOYLpwLDsWDtMoiUFZyaKamnqPGjxnpn
    url: https://api.discogs.com
    local_repository: C:\Users\Lee\Workspace\discogs data


logging:
  level:
    com:
      example:
        demo:
          jfx2: DEBUG
    org.springframework.security: DEBUG
